### ISSUE TITLE
iOS 15 also has live wallpaper file which is a .mov video located in /var/mobile/Library/SpringBoard

### ISSUE THREAD

**Issue by sadending-ios** [inyourwalls/Blossom#8]
I wonder if it would be possible if Blossom also support iOS 15

**Comment by inyourwalls** [comment]
I remember that you had to long press to activate the video. Current method won't work because ios 16 made it so the wallpaper is handled by PosterBoard and not SpringBoard. 
Anyway, this is a non jailbreak solution based on workarounds and not a standard tweak, with jailbreak on iOS 15 you can use eneko.
